version: '3.5'

services:

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./workspace
        args:
          - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
          - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
          - COMPOSER_VERSION=${WORKSPACE_COMPOSER_VERSION}
          - PUID=${WORKSPACE_PUID}
          - PGID=${WORKSPACE_PGID}
          - NODE_VERSION=${WORKSPACE_NODE_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
          - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK}
          - IMAGEMAGICK_VERSION=${IMAGEMAGICK_VERSION}
          - INSTALL_IMAGE_OPTIMIZERS=${INSTALL_IMAGE_OPTIMIZERS}
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - BASE_IMAGE_TAG_PREFIX=${WORKSPACE_BASE_IMAGE_TAG_PREFIX}
      volumes:
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
          - ./php-worker/supervisord.d:/etc/supervisord.d
      container_name: ${PROJECT_NAME}-workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "14777:14777"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php-fpm
        args:
          - PUID=${WORKSPACE_PUID}
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - BASE_IMAGE_TAG_PREFIX=${WORKSPACE_BASE_IMAGE_TAG_PREFIX}
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK}
          - INSTALL_IMAGE_OPTIMIZERS=${INSTALL_IMAGE_OPTIMIZERS}
      volumes:
          - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      container_name: ${PROJECT_NAME}-php-fpm
      ports:
          - "9003:9003"
      expose:
        - "9000"
      dns:
        - 8.8.4.4
        - 8.8.8.8
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend

### PHP Worker Container #####################################

    php-worker:
        build:
            context: ./php-worker
            args:
                - PUID=${WORKSPACE_PUID}
                - PGID=${WORKSPACE_PGID}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
                - LARADOCK_PHP_VERSION=${PHP_VERSION}
        container_name: ${PROJECT_NAME}-php-worker
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ./php-worker/supervisord.d:/etc/supervisord.d
        depends_on:
            - workspace
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
        args:
          - CONF_FILE=${NGINX_CONF_FILE}
          - PHP_UPSTREAM=php-fpm
      volumes:
          - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      container_name: ${PROJECT_NAME}-nginx
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${NGINX_HOST_TSL_PORT}:587"
        - "${NGINX_HOST_MAIL_PORT}:25"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MariaDB Container #######################################

    mariadb:
      build:
        context: ./mariadb
        args:
          - MARIADB_VERSION=${MARIADB_VERSION}
      volumes:
        - ${DATA_SAVE_PATH}/mariadb:/var/lib/mysql
      container_name: ${PROJECT_NAME}-mariadb
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend

### Memcached Container #####################################

    memcached:
      build: ./memcached
      volumes:
        - ${DATA_SAVE_PATH}/memcached:/var/lib/memcached
      container_name: ${PROJECT_NAME}-memcached
      ports:
        - "${MEMCACHED_HOST_PORT}:11211"
      depends_on:
        - php-fpm
      networks:
        - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  memcached:
    driver: "local"
  mariadb:
    driver: "local"
